version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout

      - run: cd api && npm ci
      - run: cd api && npm test

      - setup_remote_docker

      - run: cd api
      - run:
        TAG="01.${CIRCLE_BUILD_NUM}"
        LATEST="latest"
        docker build -t wouwehb/ar-multiplatformtool_api:$TAG .
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        docker push wouwehb/ar-multiplatformtool_api:$TAG
        docker tag wouwehb/ar-multiplatformtool_api:$TAG wouwehb/ar-multiplatformtool_api:$LATEST
        docker push wouwehb/ar-multiplatformtool_api:$LATEST
      



